### ISSUE TITLE
Use PSVita-StorageMgr instead of gamesdcard-microsd

### ISSUE THREAD

**Issue by Applelo** [Applelo/SwitchSD2Vita#11]

**Comment by eze92** [comment]
hi Appelelo, how are you ? , one question , will do you release a new update for 3.68 ? The store mgr isn't the same because join the partition and It dont switch and dont permitted accessing games already installed

**Comment by Applelo** [comment]
Yes, I'm working right now on version 2.0 to use PSVita-StorageMgr. I don't see the problem, StorageMgr works like gamesdcard but Switch SD2Vita will use only GCD configuration to work.

**Comment by eze92** [comment]
ah ok It's great , how you say is similar but the manual configuration maybe I did error something , I will continue waiting for you update xD . Thanks
