### ISSUE TITLE
Strange issue

### ISSUE THREAD

**Issue by ghost** [Applelo/SwitchSD2Vita#12]
So I've been re-installing HenKaku and I needed my SD2Vita re-mounted. And now the app is stuck at "Installed at ux0" and any choice except Reboot your PSVita and Exit cause the app to crash. (C2-12828-1)

**Comment by ghost** [comment]
May I add, Yosh's version does NOT fix this.

**Comment by ghost** [comment]
And I run 3.60

**Comment by Applelo** [comment]
Hello, do you use the lastest version, the 2.0 ? If the answer is yes, send me your config.txt and storage_config.txt files to check what is wrong ^^

**Comment by Minozen** [comment]
Yeah, sure. Here it is, I uploaded the both to a MEGA folder; https://mega.nz/#F!jpkjgByK!HF_UQ2gi009Ia_2o4-OGKA

**Comment by ghost** [comment]
Yeah, sure. There was no storage_config.txt, though. https://mega.nz/#F!jpkjgByK!HF_UQ2gi009Ia_2o4-OGKA

**Comment by ghost** [comment]
CLOSED. Reason: Suddenly works again for some reason. Thanks a lot Applelo for trying to help and for the fast response! You have a wonderful homebrew app!
