### ISSUE TITLE
Better switch options

### ISSUE THREAD

**Issue by Darkshadow3582** [Applelo/SwitchSD2Vita#14]
When you switch between SD2Vita to be Ux0, the official vita memory is not applied as Uma0 and when you put the official memory as ux0, the SD2vita is not set as uma0 the solution would be that by choosing the SD2vita to be ux0 put this in the config

GCD=ux0
MCD=uma0

And if you put the official as ux0
MCD=ux0
GCD=uma0

**Comment by Applelo** [comment]
Ok, I try to fix that in a next version ^^

**Comment by eze92** [comment]
Yes when use sd how official , the official don't figure how uma0 but for the contrary yes  figure correctly

**Comment by smourph** [comment]
+1 for this issue 👍

**Comment by Applelo** [comment]
[New version 2.1](https://github.com/Applelo/SwitchSD2Vita/releases/tag/2.1) fixes this issue! :)
