### ISSUE TITLE
Error ( C2-12828-1)

### ISSUE THREAD

**Issue by ghost** [Applelo/SwitchSD2Vita#15]
i keep receiving ERROR  ( C2-12828-1)  Save Core file Succeeded.

**Comment by Applelo** [comment]
What is your PSVita version ? When the problem happen ?

**Comment by ghost** [comment]
Sorry for late reply it is the slim pch 2000 
3.68

**Comment by YOKiVita** [comment]
3.68

**Comment by Applelo** [comment]
Other applications (gallery, web browser...) have this error ? Do you have ur0:/config.txt, ur0:/storage_config.txt and ur0:/storagemgr_log.txt files ? If yes, send me the files you have.

**Comment by ghost** [comment]
hi it just turned out to be backed up config texts that caused my issue now it's working thank you for  responding to me

**Comment by Applelo** [comment]
Nice, enjoy :)

**Comment by theMONK11** [comment]
i just got this issue yesterday when using SD2vita.
what config.txt backup file did u delete to get it to work again?
thanks in advance!

**Comment by Applelo** [comment]
Do you have ur0:/config.txt, ur0:/storage_config.txt and ur0:/storagemgr_log.txt files ? If yes, send me the files you have. I would like to figure out where is the problem 😃

**Comment by theMONK11** [comment]
ok thanks for the swift response!
lemme dig it up.. do i send u a screenshot? 
or the actual file?
pardon my ignorance im new here 😬

**Comment by Applelo** [comment]
If the screenshot is the error C2-12828-1, no 😆. The problem happen when your start the app? 
Yeah if you can send me your files (ur0:/config.txt, ur0:/storage_config.txt and ur0:/storagemgr_log.txt) to check if there are something wrong with them 😄

**Comment by theMONK11** [comment]
ok lemme know if this works.

Download link 
https://we.tl/t-kyNTlfB1Ku

[EDIT]
haha and yes it happens when i start the app..

**Comment by theMONK11** [comment]
haha and yes it happens when i start the app..

**Comment by Applelo** [comment]
Ok I saw your files and everything looks fine. What is your version and the model of your PSVita model ? What is the version of SwitchSD2Vita you use ?

**Comment by theMONK11** [comment]
i have the original vita..
with the trinity hack
using modoro 3.65

**Comment by Applelo** [comment]
If you have the original vita (the PCH1000) you don't need the INT configuration in your storage_config.txt but I think it will not fix the problem.
Have you tried to uninstall and reinstall the app ?
Can you try to rename the file storage_config.txt to storage_config_backup.txt, remove ur0:tai/storagemgr.skprx line in config.txt file, remove the file storagemgr.skprx and launch the app 😄

**Comment by theMONK11** [comment]
yea i tried uninstalling and installing a few times..
it worked fine up until a couple days ago..
and i also have it in my pstv and it works fine..

so i jus followed ur instructions, and even double, triple checked and made sure i did everything properly in the tai folder,
rebooted the app, and still getting the error message... 🤦‍♂️

**Comment by Applelo** [comment]
It works fine before, hum. Do you change anything made the homebrew crash like a new plugin ? 
It's really weird. I don't understand why the homebrew crash. 
Other homebrews on your PSVita works fine ?

**Comment by Applelo** [comment]
I close this issue because you don't answer. Feel free to reopen if the problem still occur.

**Comment by theMONK11** [comment]
oh my bad.. i didnt see ur last post..
yea the other homebrews work fine..
still cant get switchsd2vita to open.

-Kevin
