### ISSUE TITLE
Update Storagemgr to 3.0 version

### ISSUE THREAD

**Issue by Applelo** [Applelo/SwitchSD2Vita#16]

**Comment by eze92** [comment]
Hi , will you plan to release one update with storagemgr 3 ?

**Comment by Applelo** [comment]
Yes, it's planned of course but I don't have the time currently. I will make an update early september :)

**Comment by Applelo** [comment]
[New version 2.1](https://github.com/Applelo/SwitchSD2Vita/releases/tag/2.1) fixes this issue! :)
