### ISSUE TITLE
Use only ur0 config.txt

### ISSUE THREAD

**Issue by Applelo** [Applelo/SwitchSD2Vita#2]
When people switch between ux0 to uma0, app crash because edit the ux0. Thanks to [Yosh](https://twitter.com/Yosh778/status/898234629932634112) for the report 👍

**Comment by yosh778** [comment]
I did that but it's not so clean lol, doesn't rly matter (duplicate macros & stuff)

**Comment by Applelo** [comment]
Yeap, I will make a small update to optimize and add some small features ^^
