### ISSUE TITLE
App crash with 3.60 enso

### ISSUE THREAD

**Issue by DevX-Cipher** [Applelo/SwitchSD2Vita#22]
tried testing your application it crashes straight away when you open it on 3.60 enso firmware

**Comment by Applelo** [comment]
Really weird, it's working for me in 3.60. What kind of error you have? The homebrew crash directly when you open the app ? Do you have a ur0:/config.txt, ur0:/storage_config.txt and ur0:/storagemgr_log.txt files ? If yes, send me the files you have.

**Comment by DevX-Cipher** [comment]
yes everything is al the same as soon as you open crashes

**Comment by Applelo** [comment]
Do you have a ur0:/config.txt, ur0:/storage_config.txt and ur0:/storagemgr_log.txt files ? If yes, send me the files you have.

**Comment by Applelo** [comment]
I close the issue, reopen if you can answer me ^^
