### ISSUE TITLE
Error ( C2-12828-1)

### ISSUE THREAD

**Issue by Demasisis** [Applelo/SwitchSD2Vita#28]
Помогите пожалуста  , все пробывал и форматировал , языки менял
![Uploading IMG_2022_01_09_14_44_37_7001840182233439848998.jpg…]()
 , очистивал coocek  , до заводских настроеек сбрасывал  выскакивает эта ошибка в игре urban trial frestyle

**Comment by Applelo** [comment]
Create a new issue in english please.
