### ISSUE TITLE
Unable to switch: error C2-12828-1

### ISSUE THREAD

**Issue by mickael28** [Applelo/SwitchSD2Vita#4]
Thanks for the app. I'm currently facing the following issue, do you know why it could be? or if I could do anything from my end to workaround it?

When I click on 'switch to ux0' I get:
"An error has occurred in the following application. 
(C2-12828-1)
Saved Core File Succeeded. 
ux0:data/psp2core-1503152107-0x0000092f2d-eboot.bin.psp2dmp"

PS: same error when clicking 'switch to uma0'

**Comment by Xykun** [comment]
Got the same error making the app crash, but saved to 0x0000514ecb-eboot.bin.psp2dmp" instead (mentioning it in case it makes any difference).
Thank you for your work btw, pretty good idea to make such an app !

**Comment by Applelo** [comment]
Use the [Yosh version](https://github.com/yosh778/SwitchSD2Vita) It fix this problem ;)
