### ISSUE TITLE
last version 1.3 Not Work 

### ISSUE THREAD

**Issue by SiTWulf** [Applelo/SwitchSD2Vita#7]
When i use it in UX0 the Vita never boot... only show the enso logo and reboot again to enso logo.

**Comment by Applelo** [comment]
I hope your vita are not bricked :s It's very weird. This custom firmware is not very stable... Ok I remove this version to check what is wrong ^^ Thanks for the feedback.

**Comment by SiTWulf** [comment]
No... not bricked... is easy to bypass this problem with Plugins... only need to hold "L" while Enso logo appears and not load any plugin.

This one works like a charm:
https://github.com/ArkSource/gamecard-microsd/releases
Make the sd2vita mount in UX0 and Original Sony in UMA0.

is easy to modify the code if you check it...
`static SceIoDevice uma_ux0_dev = { "ux0:", "exfatux0", "sdstor0:gcd-lp-ign-entire", "sdstor0:gcd-lp-ign-entire", MOUNT_POINT_ID };
static SceIoDevice uma_uma0_dev = { "uma0:", "exfatuma0", "sdstor0:xmc-lp-ign-userext", "sdstor0:xmc-lp-ign-userext", MOUNT_POINT_ID2 };`

**Comment by Applelo** [comment]
I am reassured that your PSVita is not bricked 💛 Ok I don't know what is wrong because I use The_FloW version (SD2Vita for ux0) and the ArkSource version (SD2Vita for uma0) 😢 
[Edit] Oh it's the opposite 😨

**Comment by SiTWulf** [comment]
If you need to test any version... tell me... i can check.
I have SD2Vita (128GB) and 32GB Original Sony.

Better to have the two working... and switch sd2vita UX0 to UMA0, and always have the Original mounted.

**Comment by pepsypollo** [comment]
I made a version just changing the line you said and it mounts the sd as uma0 tested and working 👍 
[gamesd_uma0.zip](https://github.com/Applelo/SwitchSD2Vita/files/1806651/gamesd_uma0.zip)

**Comment by kenshin088** [comment]
The fix is easy. 

1) Generate both skrpx in SwitchSD2Vita

2) Download gamesd.skprx from TheFl0w

3) Rename it to gamesd_uma0.skprx 

4) Replace gamesd_uma0.skprx in tai folder

5) Make new text file. Rename it to gamesd_ux0.skprx

6) Replace it with gamesd_ux0.skprx in tai folder.

Can switch easily within the app now.

**Comment by pepsypollo** [comment]
Yes that would help you to change between them but won't mount sdcard as uma0 when the original card is mounted as ux0 just use the plugin I uploaded or just wait until it's fixed, I already forked a fix.

**Comment by Applelo** [comment]
I merge update by @pepsypollo (thanks to him), now the problem is fixed.

**Comment by eze92** [comment]
hello was trying and although it lets me change the original memory and does not let me do it the opposite way as I could before, you could notice plese

**Comment by pepsypollo** [comment]
I tested it again and had no problem with it try downloading version 1.3 again and select uninstall when you open the app, after that use it normally

**Comment by eze92** [comment]
I had a error in config file , now working perfect , thank so much for work and tool
